os:
  - "WMF 5"

branches:
  only:
    - master

install:
  - ps: |
      $null = Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      $null = Install-Module -Name Pester -MinimumVersion 3.4.0 -Scope CurrentUser -Force
      $null = Install-Module -Name psake -Scope CurrentUser -Force
      $null = Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force
      $null = Install-Module -Name platyPS -Scope CurrentUser -Force

build_script:
  - ps: |
      $TestResultsFile = Join-Path $pwd -ChildPath "$PSScriptRoot/TestResults.xml"
      Invoke-psake build.psake.ps1 -taskList Test, BuildHelp -properties @{"TestOutputFile" = $TestResultsFile}
      if ($psake.build_success -and (Test-Path $TestResultsFile)) {
          (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $TestResultsFile)
      }
      else {
          # Terminate the script to fail the build
          $Error | Format-List * -Force
          exit 1;
      }

on_finish:
    - ps: |
        # Publish the contents of the Release folder
        $ZipPath = "$pwd\Omnicit.zip"
        Compress-Archive -Path "$pwd\Release" -DestinationPath $ZipPath
        Push-AppveyorArtifact $ZipPath
