jobs:
  - job: Test_windows2019
    pool: 
      vmImage: windows-2019
    steps: 
      - powershell: |
          ./build.ps1 -Task Test -Bootstrap -Verbose
        displayName: "Running Tests Windows 2019"
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: NUnit
          testResultsFiles: '**Release/TestsResults.xml'

  - job: Test_windows2016
    pool: 
      vmImage: vs2017-win2016
    steps: 
      - powershell: |
          ./build.ps1 -Task Test -Bootstrap -Verbose
        displayName: "Running Tests Windows 2016"
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: NUnit
          testResultsFiles: '**Release/TestsResults.xml'

  - job: Test_windows2012R2
    pool: 
      vmImage: vs2015-win2012r2
    steps: 
      - powershell: |
          ./build.ps1 -Task Test -Bootstrap -Verbose
        displayName: "Running Tests Windows 2012R2"
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: NUnit
          testResultsFiles: '**/TestsResults.xml'


  - job: Test_Ubuntu
    pool: 
      vmImage: ubuntu-latest
    steps: 
      - script: "pwsh -c ./build.ps1 -Task Test -Bootstrap -Verbose"
        displayName: "Running Tests Ubuntu"
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: NUnit
          testResultsFiles: '**/TestsResults.xml'

  - job: Test_macos
    pool: 
      vmImage: macOS-10.14
    steps: 
      - script: "pwsh -c ./build.ps1 -Task Test -Bootstrap -Verbose"
        displayName: "Running Tests MacOS"
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: NUnit
          testResultsFiles: '**/TestsResults.xml'